# select round(avg(DAILY_FEE), 0) as AVERAGE_FEE from CAR_RENTAL_COMPANY_CAR where CAR_TYPE = 'SUV';

SELECT FLOOR(AVG(DAILY_FEE) + 0.5) AS AVERAGE_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE = 'SUV';