select round(avg(DAILY_FEE), 0) as AVERAGE_FEE from CAR_RENTAL_COMPANY_CAR where CAR_TYPE = 'SUV';

-- FLOOR 해당 값보다 작거나 가장 큰 정수: FLOOR(12.7) = 12, FLOOR(12.1) = 12, FLOOR(-12.1) = -13 
# SELECT FLOOR(AVG(DAILY_FEE) + 0.5) AS AVERAGE_FEE
# FROM CAR_RENTAL_COMPANY_CAR
# WHERE CAR_TYPE = 'SUV';

-- CAST로 정수 변환
# SELECT CAST(AVG(DAILY_FEE) AS UNSIGNED) AS AVERAGE_FEE
# FROM CAR_RENTAL_COMPANY_CAR
# WHERE CAR_TYPE = 'SUV';

-- TRUNCATE로 숫자를 지정한 소수점 자리에서 잘라버리기 (0: 정수만 유지, 1: 소수 첫번째자리까지 유지)
# SELECT TRUNCATE(AVG(DAILY_FEE) + 0.5, 0) AS AVERAGE_FEE
# FROM CAR_RENTAL_COMPANY_CAR
# WHERE CAR_TYPE = 'SUV';